Replace empty object default type with any object
By default FormValues is of type `object` which is empty. When accessing a property on the values object, typescript raises the following error:

`Property 'myprop' does not exist on type 'object'.ts(2339)`

This PR fixes that.